<h3><?php echo $this->popularity['boardgame']['name']; ?></h3>

<strong><?php echo $this->popularity['popularity']; ?></strong>

<dl>
    <dt>Average score:</dt><dd><?php echo $this->popularity['score']; ?></dd>
    <dt>Total plays:</dt><dd><?php echo $this->popularity['plays']['total_plays']; ?></dd>
    <dt>Average players:</dt><dd><?php echo $this->popularity['plays']['avg_players']; ?></dd>
<dl>
